version: "3"
services:
  hmc-backend:
    container_name: my_backend
    build:
      context: .
      args:
        SERVER: development
    ports:
        - "3000:3000"
    volumes:
      - ./app:/app/server
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev

  mysql:
    image: mysql:latest
    container_name: my_db
    environment:
      MYSQL_DATABASE: hmc_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql