version: "3"
services:
  hcm-backend:
    build:
      context: .
      args:
        SERVER: development
    ports:
        - "3000:3000"
    volumes:
      - ./app:/server/app
    command: npm run dev