version: "3"
services:
  hmc-backend:
    container_name: my_backend
    build:
      context: .
      args:
        SERVER: development
    ports:
        - "3000:3000"
    volumes:
      - ./app:/app/server
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev

  mysql:
    image: mysql:latest
    container_name: my_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql   # Define a named volume here

volumes:
  mysql-data:
