version: "3"
services:
  hcm-backend:
    container_name: my_backend
    build:
      context: .
      args:
        SERVER: development
    ports:
        - "3000:3000"
    depends_on:
      - mysql_container
    volumes:
      - ./app:/server/app
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev

  mysql_container:
    image: mysql:latest
    container_name: hcm_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "33061:3306"
    volumes:
      - mysql-data:/var/lib/mysql  

volumes:
  mysql-data:
